Presentacion/Areas/Catalogo/Controllers/SerieController.cs
using System;
using System.Web.Mvc;
using Datos;
using Datos.DTO.Infraestructura.ViewModels;
using Datos.Enums;
using Datos.Recursos;
using Datos.Repositorios.Catalogos;
using Datos.Repositorios.Configuracion;
using Presentacion.Controllers;
using Sistema.Extensiones;
using Sistema.Paginador;

namespace Presentacion.Areas.Catalogo.Controllers
{
    public class SerieController : ControladorBase
    {
        public ActionResult Index(CuadroArchivisticoViewModel cuadroArchivisticoViewModel)
        {
            cuadroArchivisticoViewModel.CuadroArchivistico = new CuadroArchivistico {Habilitado = true};
            var idPadre = cuadroArchivisticoViewModel.IdPadre.DecodeFrom64().TryToInt();

            cuadroArchivisticoViewModel.IdEntidad = ObtenerParametroGetEnInt(Enumerados.Parametro.IdEntidad);

            using (var bd = new Contexto())
            {
                var archivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);

                if (idPadre > 0)
                {
                    var antecesores = archivisticoRepositorio.BuscarUnoSolo(a => a.IDCuadroArchivistico == idPadre,
                        new[]
                        {
                            "PadreCuadroArchivistico.PadreCuadroArchivistico.PadreCuadroArchivistico.PadreCuadroArchivistico"
                        });
                    cuadroArchivisticoViewModel.CuadroArchivistico.PadreCuadroArchivistico = antecesores;
                }

                if (cuadroArchivisticoViewModel.IdEntidad > 0)
                {
                    var repositorioEntidad = new EntidadRepositorio(bd);
                    cuadroArchivisticoViewModel.Entidad = repositorioEntidad.BuscarUnoSolo(e =>
                        e.IDEntidad == cuadroArchivisticoViewModel.IdEntidad);
                    cuadroArchivisticoViewModel.CuadroArchivistico.Habilitado = true;
                }

                cuadroArchivisticoViewModel.CuadroArchivistico.IDPadreCuadroArchivistico = idPadre;
                cuadroArchivisticoViewModel.CuadroArchivistico.IDTipoCuadroArchivistico = (int)TiposCuadroArchivistico.Serie;
                cuadroArchivisticoViewModel.CuadroArchivisticos = archivisticoRepositorio.Buscar(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.TotalEncontrados = archivisticoRepositorio.ObtenerTotalRegistros(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.Paginas = Paginar.ObtenerCantidadPaginas(cuadroArchivisticoViewModel.TotalEncontrados, cuadroArchivisticoViewModel.TamanoPagina);
            }

            return View(cuadroArchivisticoViewModel);
        }

        [HttpPost]
        public ActionResult Index(CuadroArchivisticoViewModel cuadroArchivisticoViewModel, string pagina)
        {
            if (string.IsNullOrEmpty(pagina)) pagina = "1";
            cuadroArchivisticoViewModel.PaginaActual = pagina.TryToInt();

            var idPadre = cuadroArchivisticoViewModel.IdPadre.DecodeFrom64().TryToInt();
            cuadroArchivisticoViewModel.IdEntidad = ObtenerParametroGetEnInt(Enumerados.Parametro.IdEntidad);

            using (var bd = new Contexto())
            {
                var archivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);

                if (idPadre > 0)
                {
                    var antecesores = archivisticoRepositorio.BuscarUnoSolo(a => a.IDCuadroArchivistico == idPadre,
                        new[]
                        {
                            "PadreCuadroArchivistico.PadreCuadroArchivistico.PadreCuadroArchivistico.PadreCuadroArchivistico"
                        });
                    cuadroArchivisticoViewModel.CuadroArchivistico.PadreCuadroArchivistico = antecesores;
                }

                if (cuadroArchivisticoViewModel.IdEntidad > 0)
                {
                    var repositorioEntidad = new EntidadRepositorio(bd);
                    cuadroArchivisticoViewModel.Entidad = repositorioEntidad.BuscarUnoSolo(e =>
                        e.IDEntidad == cuadroArchivisticoViewModel.IdEntidad);
                    cuadroArchivisticoViewModel.CuadroArchivistico.Habilitado = true;
                }

                cuadroArchivisticoViewModel.CuadroArchivistico.IDPadreCuadroArchivistico = idPadre;
                cuadroArchivisticoViewModel.CuadroArchivistico.IDTipoCuadroArchivistico = (int)TiposCuadroArchivistico.Serie;
                cuadroArchivisticoViewModel.CuadroArchivisticos = archivisticoRepositorio.Buscar(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.TotalEncontrados = archivisticoRepositorio.ObtenerTotalRegistros(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.Paginas = Paginar.ObtenerCantidadPaginas(cuadroArchivisticoViewModel.TotalEncontrados,
                    cuadroArchivisticoViewModel.TamanoPagina);
            }

            LimpiarModelState();

            return View(cuadroArchivisticoViewModel);
        }

        public ActionResult Guardar(string idCuadroArchivistico, string idPadre, string idEntidadRegresar)
        {
            var idCuadroArchivisticoBuscar = idCuadroArchivistico.DecodeFrom64().TryToInt();
            var idEntidad = idEntidadRegresar.DecodeFrom64().TryToInt();

            var viewModel = new GuardarCuadroArchivisticoViewModel {IdPadre = idPadre.DecodeFrom64().TryToInt()};

            using (var bd = new Contexto())
            {
                var archivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);

                CuadroArchivistico cuadroArchivistico;
                if (idCuadroArchivisticoBuscar > 0)
                {                   
                    cuadroArchivistico = archivisticoRepositorio
                        .BuscarPorIdCuadroArchivistico(idCuadroArchivisticoBuscar);
                    viewModel.EstablecerIdAntecesores(cuadroArchivistico);
                }
                else
                {
                    cuadroArchivistico = new CuadroArchivistico();

                    if (viewModel.IdPadre > 0)
                    {
                        var antecesores = archivisticoRepositorio.BuscarUnoSolo(a => a.IDCuadroArchivistico == viewModel.IdPadre,
                            new[]
                            {
                                "PadreCuadroArchivistico.PadreCuadroArchivistico.PadreCuadroArchivistico.PadreCuadroArchivistico"
                            });

                        viewModel.EstablecerIdAntecesores(antecesores);
                    }
                }
                
                viewModel.CuadroArchivistico = cuadroArchivistico;
                ViewBag.IdEntidadRegresar = idEntidad;

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Guardar(GuardarCuadroArchivisticoViewModel viewModel, string idPadre)
        {
            var idCuadroArchivistico = ObtenerParametroGetEnInt(Enumerados.Parametro.IdCuadroArchivistico);
            viewModel.IdPadre = Request.QueryString["idPadre"].DecodeFrom64().TryToInt();

            var idEntidad = Request.QueryString["idEntidadRegresar"].DecodeFrom64().TryToInt();

            var cuadroArchivistico = viewModel.CuadroArchivistico;

            if (viewModel.IdSubseccion > 0)
            {
                cuadroArchivistico.IDPadreCuadroArchivistico = viewModel.IdSubseccion;
            }
            else if (viewModel.IdSeccion > 0)
            {
                cuadroArchivistico.IDPadreCuadroArchivistico = viewModel.IdSeccion;
            }

            using (var bd = new Contexto())
            {
                var cuadroarchivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);
                cuadroArchivistico.IDCuadroArchivistico = idCuadroArchivistico;
                cuadroArchivistico.IDTipoCuadroArchivistico = (int)TiposCuadroArchivistico.Serie;
                AccionesAuditoria accion;
                if (cuadroArchivistico.IDCuadroArchivistico > 0)
                {
                    cuadroArchivistico.FechaModificado = DateTime.Now;
                    cuadroarchivisticoRepositorio.Modificar(cuadroArchivistico);
                    EscribirCorrectoMensaje(General.GuardadoCorrecto);
                    accion = AccionesAuditoria.Modificar;
                }
                else
                {
                    cuadroArchivistico.Habilitado = true;
                    cuadroArchivistico.FechaCreacion = DateTime.Now;
                    cuadroArchivistico.FechaModificado = cuadroArchivistico.FechaCreacion;
                    cuadroarchivisticoRepositorio.Guardar(cuadroArchivistico);
                    EscribirCorrectoMensaje(General.GuardadoCorrecto);

                    accion = AccionesAuditoria.Guardar;
                }
                GuardarMovimientoAuditoria(cuadroArchivistico.IDCuadroArchivistico, ModulosAuditoria.Series, accion, cuadroArchivistico.Nombre);
                bd.SaveChanges();
            }

            var parametrosGet = new
            {
                idCuadroArchivistico = cuadroArchivistico.IDCuadroArchivistico.ToString().EncodeTo64(),
                idPadre = viewModel.IdPadre.ToString().EncodeTo64(),
                idEntidadRegresar = idEntidad.ToString().EncodeTo64()
            };

            return RedirectToAction("Guardar", parametrosGet);
        }

        public ActionResult Habilitar(string idCuadroarchivistico, string idPadre)
        {
            var idCuadroarchivisticoHabilitar = idCuadroarchivistico.DecodeFrom64().TryToInt();

            using (var bd = new Contexto())
            {
                var cuadroarchivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);
                cuadroarchivisticoRepositorio.CambiarHabilitado(idCuadroarchivisticoHabilitar, true);
                EscribirCorrectoMensaje(General.HabilitadoCorrecto);

Presentacion/Areas/Catalogo/Views/Seccion/Guardar.cshtml
@using Datos
@using Datos.Recursos
@using Datos.Repositorios.Configuracion
@using Presentacion.Helpers
@using Sistema.Extensiones
@model Datos.DTO.Infraestructura.ViewModels.GuardarCuadroArchivisticoViewModel

@{
    ViewBag.Title = General.GuardarSeccion;
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-8 col-lg-7">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            @if (Model?.CuadroArchivistico.IDCuadroArchivistico > 0)
                            {
                                <h5>Editar datos del nuevo fondo</h5>
                            }
                            else
                            {
                                <h5>Datos del nuevo fondo</h5>
                            }
                        </div>
                    </div>
                </div>
                <div class="ibox-content form-horizontal">
                    <div class="row">
                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.CuadroArchivistico.Clave, "Clave")
                        </div>
                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
                            @Html.TextBoxFor(m => m.CuadroArchivistico.Clave, new { @class = "form-control input-sm", @data_validation = "required,length", @data_validation_length = "max10", maxlength = "10" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.CuadroArchivistico.Nombre, "Nombre")
                        </div>
                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
                            @Html.TextBoxFor(m => m.CuadroArchivistico.Nombre, new { @class = "form-control input-sm", @data_validation = "required,length", @data_validation_length = "max80", maxlength = "80" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-md-3">
                            <label for="Fondo">Fondo:</label>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @{
                                var fondos = CuadroArchivisticoRepositorio.BuscarTipo(TiposCuadroArchivistico.Fondo);
                                if (fondos.Count == 2) { Model.IdFondo = fondos.Last().Value.ToInt(); }
                            }
                            @Html.DropDownListFor(m => m.IdFondo, fondos, new { @class = "form-control input-sm" })
                        </div>
                    </div>
                    <div class="row @(Model.IdFondo > 0 ? string.Empty : "hidden")">
                        <div class="col-xs-12 col-md-3">
                            <label for="IdSubFondo">Subfondo:</label>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @Html.CuadroArchivisticoDdl(m => m.IdSubfondo, Model.IdFondo, TiposCuadroArchivistico.Subfondo)
                        </div>
                    </div>
                </div>
                <div class="ibox-footer">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="pull-right">
                                @if (Model.IdPadre > 0)
                                {

                                    @Html.ActionLinkCifradoConTexto(General.Regresar, "Index", "Seccion", "Catalogo", "btn btn-default btn-sm", "fa fa-angle-double-left",
                                        new Dictionary<string, int> { { "idPadre", Model.IdPadre } })
                                }
                                else
                                {
                                    @Html.ActionLinkCifradoConTexto(General.Regresar, "Index", "Seccion", "Catalogo", "btn btn-default btn-sm", "fa fa-angle-double-left")
                                }
                                <button class="btn btn-primary btn-sm">
                                    <i class="fa fa-save"></i> @Resources.General.Guardar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<!-- Footer Scripts -->
@section FooterScripts{
    <script type="text/javascript">
        $.validate({
            language: es,
            modules: 'security'
        });
    </script>
}
<!-- End Footer Scripts -->

Presentacion/Areas/Catalogo/Views/Seccion/Index.cshtml
@using Datos
@using Datos.Recursos
@using Datos.Repositorios.Configuracion
@using Presentacion.Helpers
@using Sistema.Extensiones

@model Datos.DTO.Infraestructura.ViewModels.CuadroArchivisticoViewModel

@{
    ViewBag.Title = Resources.General.BuscarSeccion;
}

@using (Html.BeginForm())
{
    <div class="tarjeta">
        <div class="row">
            <div class="col-xs-12 col-md-6 form-horizontal">
                <div class="col-xs-12 col-md-12 form-horizontal">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-3">
                            <label for="Clave">Clave:</label>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @Html.TextBoxFor(m => m.CuadroArchivistico.Clave, new { @class = "form-control input-sm" })
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12 form-horizontal">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-3">

                        </div>
                        <div class="col-xs-12 col-md-9">
                            <div class="checkbox checkbox-success">
                                @Html.CheckBoxFor(m => m.CuadroArchivistico.Habilitado)
                                @Html.LabelFor(m => m.CuadroArchivistico.Habilitado)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 form-horizontal">
            @if (Model.CuadroArchivistico.IDPadreCuadroArchivistico == 0)
            {
                <div class="col-xs-12 col-md-12 form-horizontal">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-3">
                            <label for="IdFondo">Fondo:</label>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @{
                                var fondos = CuadroArchivisticoRepositorio.BuscarTipo(TiposCuadroArchivistico.Fondo);
                                if (fondos.Count == 2) { Model.IdFondo = fondos.Last().Value.ToInt(); }
                            }
                            @Html.DropDownListFor(m => m.IdFondo, fondos, new { @class = "form-control input-sm" })
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12 form-horizontal">
                    <div class="form-group @(Model.IdFondo > 0 ? string.Empty : "hidden")">
                        <div class="col-xs-12 col-md-3">
                            Subfondo:
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @Html.CuadroArchivisticoDdl(m => m.IdSubfondo, Model.IdFondo, TiposCuadroArchivistico.Subfondo)
                        </div>
                    </div>
                </div>
            }
                <div class="col-xs-12 col-md-12">
                    @Html.ActionLinkCifradoConTexto("Nuevo", "Guardar", "Seccion", "Catalogo",
                        "btn btn-sm btn-default pull-right m-l-5", "fa fa-plus",
                        new Dictionary<string, int> {{"IdPadre", Model.CuadroArchivistico.IDPadreCuadroArchivistico ?? 0 } })
                    <button class="btn btn-sm btn-primary pull-right"><i class="fa fa-search"></i> @Resources.General.Buscar</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-12 m-t-10 m-b-10 ">
                <div class="col-md-6 bold">
                    @Html.DropDownListFor(m => m.TamanoPagina, Sistema.Listas.ObtenerListaCantidadPagina())
                    @Resources.General.TamanoPagina
                </div>
                <div class="col-md-6 text-right">
                    <label class="label label-success">
                        @Resources.General.Encontrados: @Model.TotalEncontrados
                    </label>
                </div>
            </div>
        </div>
        
        @if (Model.CuadroArchivistico.IDPadreCuadroArchivistico > 0)
        {
            <div class="row">
                <div class="col-xs-12 col-md-9 form-horizontal">
                    <div class="col-xs-12 col-md-12 form-horizontal">
                        <ul class="breadcrumb f-s-14">
                            <li>
                                @Html.ActionLinkCifradoConTexto("Cuadro Archivístico", "Index", "Fondo", "Catalogo", string.Empty, string.Empty)
                            </li>
                            @foreach (var migaja in Model.ObtenerRuta())
                            {
                                <li>
                                    @Html.ActionLinkCifradoConTexto(migaja.Nombre, "Index", migaja.Tipo, "Catalogo", string.Empty,
                                        string.Empty, new Dictionary<string, int> { { "idPadre", migaja.Id } })
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }

        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="table-responsive no-borders">
                    <table class="table table-hover table-striped min-w-700" id="tblBusqueda">
                        <thead>
                        <tr>
                            <th>Sección</th>
                            <th class="hidden subfondo">Subfondo</th>
                            <th>Fondo</th>
                            <th>Fecha de creacion</th>
                            <th>Fecha de modificacion</th>
                            <th class="text-center">@Resources.General.Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if (Model != null)
                        {
                            Model.ExisteSubfondo = false;

                            foreach (var cuadroArchivistico in Model.CuadroArchivisticos)
                            {
                                cuadroArchivistico.GenerarJerarquia();
                                var seccion = cuadroArchivistico.CuadroArchivistico;

                                var subfondo = Model.ObtenerTipo(seccion, TiposCuadroArchivistico.Subfondo);
                                var fondo = Model.ObtenerTipo(seccion, TiposCuadroArchivistico.Fondo);

                                if (subfondo != null) { Model.ExisteSubfondo = true; }

                                <tr>
                                    <td>
                                        <strong>@seccion.Clave</strong>
                                        <br/>
                                        @seccion.Nombre
                                    </td>                                   
                                    <td class="hidden subfondo">@(subfondo != null ? subfondo.Nombre : string.Empty)</td>
                                    <td>@fondo.Nombre</td>
                                    <td>@seccion.FechaCreacion.Date.ToString("d")</td>
                                    <td>@seccion.FechaModificado.Date.ToString("d")</td>
                                    <td class="text-center">
                                        @if (seccion.Habilitado)
                                        {
                                            @Html.ActionLinkCifrado(General.Modificar, "Guardar", "Seccion", "Catalogo",
                                                "btn btn-warning btn-circle m-l-2 m-r-2", "fa fa-pencil",
                                                new Dictionary<string, int> {
                                                    { "IDCuadroArchivistico", seccion.IDCuadroArchivistico},
                                                    { "IdPadre", Model.IdPadre.DecodeFrom64().TryToInt()}
                                                })

                                            @Html.ActionLinkCifrado(Resources.General.Deshabilitar, "Deshabilitar", "Seccion", "Catalogo",
                                                "btn btn-danger btn-circle m-l-2 m-r-2 deshabilitar", "fa fa-times",
                                                new Dictionary<string, int>
                                                {
                                                    { "IDCuadroArchivistico", seccion.IDCuadroArchivistico },
                                                    {"IdPadre", Model.IdPadre.DecodeFrom64().TryToInt() }
                                                }, new { @id = "btnEliminar", @name = seccion.IDCuadroArchivistico })              
                                        }
                                        else
                                        {
                                            @Html.ActionLinkCifrado(Resources.General.Habilitar, "Habilitar", "Seccion", "Catalogo",
                                                "btn btn-primary btn-circle habilitar", "fa fa-check",
                                                new Dictionary<string, int> { { "IDCuadroArchivistico", seccion.IDCuadroArchivistico } })
                                        }
                                        <a class="btn btn-success btn-circle" title="Ver subsecciones"
                                           href="@Url.Action("Index", "Subseccion", new {idPadre = seccion.IDCuadroArchivistico.ToString().EncodeTo64()})">
                                            SS
                                        </a>
                                        <a class="btn btn-success btn-circle" title="Ver series"
                                           href="@Url.Action("Index", "Serie", new {idPadre = seccion.IDCuadroArchivistico.ToString().EncodeTo64()})">
                                            Se
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                        </tbody>
                    </table>
                </div>
                <div>
                    @Html.Partial("Controls/_Paginacion", Model)
                </div>
            </div>
        </div>
    </div>
                   
}

<script type="text/javascript">
    @section DocumentOnReady
    {
        @if (Model.ExisteSubfondo)
        {
            @:$(".hidden.subfondo").removeClass("hidden");
        }

    $("#tblBusqueda").tablesorter();
    
    $(document).off("click", "#btnEliminar");
    $(document).on("click", "#btnEliminar", function (e) {

        e.preventDefault();
        var href = this.href;

        swal({
            title: "¡Atención!",
            text: "¿Esta seguro que desea deshabilitar esta Seccion?",
            type: "warning",
            showCancelButton: true,
            cancelButtonText: "Cancelar",
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Aceptar",
            closeOnConfirm: false
        },
        function () {
            window.location.href = href;
            return true;
        });
    });
}
</script>

<script language="JavaScript">
    function CambiarFormulario() {
        var civil = document.getElementById('Lista');//cogemos los campos
        var tc1 = document.getElementById('TextoSubfondo');
        tc1.disabled = true;
        if (civil.selectedIndex > 0) {//si no escogió casado
            tc1.disabled = false;//se desactivan los campos
        } else {//si escogió casado
            tc1.disabled = true;//se quedan los campos activos
        }
    }

</script>