Presentacion/Controllers/InicioController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Services;
using Datos;
using Datos.DTO.Infraestructura.ViewModels;
using Datos.Repositorios.Catalogos;
using Datos.Repositorios.Reportes;
using Negocio.Servicios;
using Sistema;

namespace Presentacion.Controllers
{
    public class InicioController : ControladorBase
    {
        [HttpGet]
        public ActionResult Index()
        {
            var viewModel = new InicioViewModel();

            var idEntidad = ObtenerSesion().IdEntidad;
            var fechaInicio = DateTime.Now.AddDays(-31);
            var fechaFin = DateTime.Now.Date.AddDays(1).AddMilliseconds(-1);

            var anio = DateTime.Now.Year;
            var mes = DateTime.Now.Month;

            var fechaMesInicio = new DateTime(anio, mes, 1);
            var fechaMesFin = new DateTime(anio, mes, DateTime.DaysInMonth(anio, mes), 23, 59, 59);

            var fechaInicioGrafica = fechaMesInicio.AddMonths(-6);

            using (var contexto = new Contexto())
            {
                if (idEntidad > 0)
                {
                    var repositorioEntidad = new EntidadRepositorio(contexto);
                    viewModel.NombreEntidad = repositorioEntidad.ObtenerPropiedadUno(e => e.IDEntidad == idEntidad,
                        e => e.Nombre);
                }

                var repositorio = new ReportesRepositorio(contexto);

                viewModel.MesActual = FechaUtilidades.ObtenerNombreMes(DateTime.Now.Month);

                viewModel.CantidadMesDigitalizados = repositorio.ObtenerTotalDigitalizados(idEntidad, fechaMesInicio, fechaMesFin);
                viewModel.TotalExpedientes = repositorio.ObtenerTotalExpedientes(idEntidad);
                viewModel.CantidadPromedioDigitalizadosDia = repositorio.ObtenerDigitalizadosPromedioDia(idEntidad, fechaInicio, fechaFin);
                viewModel.PromedioConsultasDiarias = repositorio.ObtenerPromedioConsultasDiarias(idEntidad);
                viewModel.PromedioConsultasMes = repositorio.ObtenerPromedioConsultasMeses(idEntidad);
                viewModel.MásConsultados = repositorio.ObtenerExpedientesMasConsultados(idEntidad);

                var consultaMeses = repositorio.ObtenerMesesDigitalizados(idEntidad, fechaInicioGrafica, fechaMesFin);
                viewModel.CantidadDigitalizadosPorMes = ServiciosEstadisticas.RellenarMeses(consultaMeses, fechaInicioGrafica, fechaMesFin);
            }

            return View(viewModel);
        }

        [WebMethod]
        [HttpPost]
        public JsonResult ObtenerExpedientesMasConsultados(string tipo)
        {
            var fechaInicio = DateTime.Now;
            var fechaFin = DateTime.Now;

            var anio = fechaInicio.Year;
            var mes = fechaInicio.Month;

            var idEntidad = ObtenerSesion().IdEntidad;

            switch (tipo)
            {
                case "Dia":
                    fechaInicio = DateTime.Now.Date;
                    fechaFin = fechaInicio.AddDays(1).AddMilliseconds(-1);
                    break;
                case "Semana":
                    fechaInicio = DateTime.Now.Date;
                    fechaFin = fechaInicio.AddDays(1).AddMilliseconds(-1);
                    fechaInicio = fechaInicio.AddDays(-6);
                    break;
                case "Mes":
                    fechaInicio = new DateTime(anio, mes, 1);
                    fechaFin = new DateTime(anio, mes, DateTime.DaysInMonth(anio, mes), 23, 59, 59);
                    break;
                case "Anio":
                    fechaInicio = new DateTime(anio, 1, 1);
                    fechaFin = new DateTime(anio, 12, 31, 23, 59, 59);
                    break;
            }

            using (var bd = new Contexto())
            {
                var repositorio = new ReportesRepositorio(bd);

                var digitalizacionMeses = tipo == "Siempre"
                    ? repositorio.ObtenerExpedientesMasConsultados(idEntidad)
                    : repositorio.ObtenerExpedientesMasConsultados(idEntidad, fechaInicio, fechaFin);

                return Json(digitalizacionMeses);
            }
        }
    }
}

Presentacion/Views/Inicio/Index.cshtml
@using Datos
@using Datos.DTO.Infraestructura.ViewModels
@using Presentacion.Helpers
@using Sistema
@model InicioViewModel

@{
    ViewBag.Title = Resources.General.Inicio;
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div>
                                <span class="pull-right text-right">
                                    @if (Model.NombreEntidad != null)
                                    {
                                        <small>Entidad: <strong>@Model.NombreEntidad</strong></small>
                                    }
                                    <br>
                                    Total: @(Model.TotalExpedientes) expedientes
                                </span>
                                <h1 class="m-b-xs">@(Model.CantidadMesDigitalizados) expedientes</h1>
                                <h3 class="font-bold no-margins">
                                    Digitalizados en el mes de @Model.MesActual
                                </h3>
                            </div>

                            <div class="p-t-10">
                                <iframe class="chartjs-hidden-iframe" style="width: 100%; display: block; border: 0px; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>
                                <canvas id="lineChart" height="152" style="display: block; width: 654px; height: 152px;" width="654"></canvas>
                            </div>

                            <div class="m-t-md">
                                <small class="pull-right">
                                    <i class="fa fa-clock-o"> </i>
                                    Actualizado @DateTime.Now.ToString("dd.MM.yyyy")
                                </small>
                                <small>
                                    <strong>Explicación:</strong> Cantidad de expedientes digitalizados en los últimos meses.
                                </small>
                            </div>
                        </div>
                        <div class="col-md-12"><hr/></div>
                        <div class="col-md-12">
                            <div class="col-md-4 col-sm-4">
                                <ul class="stat-list">
                                    <li class="text-center">
                                        <h2 class="no-margins">@(Model.CantidadPromedioDigitalizadosDia)</h2>
                                        <strong>Promedio digitalización por día</strong>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-4 col-sm-4">
                                <ul class="stat-list">
                                    <li class="text-center">
                                        <h2 class="no-margins">@(Model.PromedioConsultasDiarias)</h2>
                                        <strong>Promedio de consultas diarias</strong>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-4 col-sm-4">
                                <ul class="stat-list">
                                    <li class="text-center">
                                        <h2 class="no-margins ">@(Model.PromedioConsultasDiarias)</h2>
                                        <strong>Promedio de consultas por mes</strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Expedientes más consultados</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-9 m-b-xs">
                            <div data-toggle="buttons" class="btn-group">
                                <label class="btn btn-sm btn-white active">
                                    <input type="radio" id="opcionDia" name="opcionesMasConsultados" value="Siempre">Siempre
                                </label>
                                <label class="btn btn-sm btn-white">
                                    <input type="radio" id="opcionDia" name="opcionesMasConsultados" value="Dia">Día
                                </label>
                                <label class="btn btn-sm btn-white">
                                    <input type="radio" id="opcionSemana" name="opcionesMasConsultados" value="Semana">Semana
                                </label>
                                <label class="btn btn-sm btn-white">
                                    <input type="radio" id="opcionMes" name="opcionesMasConsultados" value="Mes">Mes
                                </label>
                                <label class="btn btn-sm btn-white">
                                    <input type="radio" id="opcionAnio" name="opcionesMasConsultados" value="Anio">Año
                                </label>
                            </div>
                            <label id="labelCargando" class="hidden">Cargando...</label>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped" id="tablaExpedientes">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Expediente</th>
                                <th>Estado</th>
                                <th>Entidad</th>
                                <th class="text-center"># Consultas</th>
                                <th class="text-center">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @{ var posicion = 1; }
                            @foreach (var expediente in Model.MásConsultados)
                            {
                                <tr>
                                    <td>@posicion</td>
                                    <td>
                                        <strong>E@(expediente.NumeroExpediente)</strong>
                                        <br />
                                        <strong>@expediente.Titulo</strong>
                                        <br />
                                        <small>S: @expediente.CuadroArchivistico</small>
                                        <br/>
                                        <small>DD: @expediente.DisposicionDocumental</small>
                                        <br/>
                                        <small>VD: @expediente.ValorDocumental</small>
                                    </td>
                                    <td>@expediente.EstadoExpediente</td>
                                    <td>@expediente.Entidad</td>
                                    <td class="text-center">@expediente.CantidadConsulta</td>
                                    <td class="text-center">
                                        @Html.ActionLink(Resources.General.Detalles, "detalles", "#","btn btn-info btn-circle", "fa fa-search")
                                        @Html.HiddenCifrado("IdExpediente", expediente.IDExpediente.ToString())
                                        @Html.ActionLinkCifrado(Resources.General.Consultar, "Consultar", "Expediente", "Digitalizacion",
                                            "btn btn-success btn-circle m-l-2 m-r-2", "fa fa-chevron-right",
                                            new Dictionary<string, int>
                                            {
                                                {"IdExpediente", expediente.IDExpediente}
                                            })
                                    </td>
                                </tr>

                                posicion++;
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Html.Partial("Expediente/_DetallesExpediente")
}

@section FooterScripts {
    <script type="text/javascript" src="~/Content/js/chartJs/Chart.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $("#tablaExpedientes").on("click", "tbody .detalles", function (e) {
                e.preventDefault();
                var id = $(this).parent().find("input[type=hidden]").val();
                detallesExpediente.Buscar(id);
            });

            var labels = [];
            var data = [];

            @foreach (var mes in Model.CantidadDigitalizadosPorMes)
            {
                @:labels.push("@(FechaUtilidades.ObtenerNombreMes(mes.Mes.Value))");
                @:data.push("@(mes.Cantidad ?? 0)");
            }

            var lineData = {
                labels: labels,
                datasets: [
                    {
                        label: "Example dataset",
                        fillColor: "rgba(26,179,148,0.5)",
                        strokeColor: "rgba(26,179,148,0.7)",
                        pointColor: "rgba(26,179,148,1)",
                        pointStrokeColor: "#fff",
                        pointHighlightFill: "#fff",
                        pointHighlightStroke: "rgba(26,179,148,1)",
                        data: data
                    }
                ]
            };

            var lineOptions = {
                scaleShowGridLines: true,
                scaleGridLineColor: "rgba(0,0,0,.05)",
                scaleGridLineWidth: 1,
                bezierCurve: true,
                bezierCurveTension: 0.4,
                pointDot: true,
                pointDotRadius: 4,
                pointDotStrokeWidth: 1,
                pointHitDetectionRadius: 20,
                datasetStroke: true,
                datasetStrokeWidth: 2,
                datasetFill: true,
                responsive: true,
            };

            var ctx = document.getElementById("lineChart").getContext("2d");
            var myNewChart = new Chart(ctx).Line(lineData, lineOptions);

            $("input[name='opcionesMasConsultados']").change(function() {
                var tipo = $(this).val();

                $.ajax({
                    url: '@Url.Action("ObtenerExpedientesMasConsultados", "Inicio", new {area = ""})',
                    data: "{tipo : '" + tipo + "' }",
                    dataType: "json",
                    contentType: "application/json",
                    type: "POST",
                    beforeSend: function() {
                        $("#labelCargando").removeClass("hidden");
                    },
                    success: function(data) {
                        var html = "";
                        var posicion = 1;

                        data.forEach(function(expediente) {
                            html += "<tr>" +
                                "<td>" + posicion + "</td>" +
                                "<td><strong>E" + expediente.NumeroExpediente + "</strong>" +
                                "<br/><strong>" + expediente.Titulo + "</strong>" +
                                "<br/><small>S: " + expediente.CuadroArchivistico + "</small>" +
                                "<br/><small>DD: " + expediente.DisposicionDocumental + "</small>" +
                                "<br/><small>VD: " + expediente.ValorDocumental + "</small></td>" +
                                "<td>" + expediente.EstadoExpediente + "</td>" +
                                "<td>" + expediente.Entidad + "</td>" +
                                "<td class='text-center'>" + expediente.CantidadConsulta +"</td>" +
                                "<td class='text-center'> <a class='btn btn-info btn-circle detalles' href= '#' id= 'detalles' title='Detalles'> <i class='fa fa-search'> </i> </a>" +
                                "<input id='IdExpediente' type='hidden' value=" + expediente.Id64Expediente +">" +
                                "<a class='btn btn-success btn-circle m-l-2 m-r-2' href='/Digitalizacion/Expediente/Consultar?IdExpediente=" + expediente.Id64Expediente +
                                "'title='Consultar' > <i class='fa fa-chevron-right'> </i> </a> </td>" +
                                "</tr>";

                            posicion++;
                        });

                        var tablaExpedientes = $("#tablaExpedientes tbody");
                        tablaExpedientes.html("");
                        tablaExpedientes.append(html);
                    },
       
                complete: function() {
                    $("#labelCargando").addClass("hidden");
                }
            });
        });
    });
</script>
}