Presentacion/Areas/Reportes/Controllers/CadidoController.cs
using System.IO;
using System.Web.Mvc;
using Datos;
using Datos.DTO.Infraestructura.ViewModels;
using Negocio.Servicios;
using Presentacion.Controllers;
using Sistema;

namespace Presentacion.Areas.Reportes.Controllers
{
    public class CadidoController : ControladorBase
    {
        [HttpGet]
        public ActionResult Index()
        {
            var viewModel = new CadidoViewModel
            {
                Cadido = new Cadido
                {
                    Habilitado = true,
                    EsAdministrativo = true,
                    EsLegal = true,
                    EsContableFiscal = true
                },
                IdEntidad = ObtenerSesion().IdEntidad
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(CadidoViewModel viewModel)
        {
            viewModel.Cadido.Habilitado = true;

            var idEntidad = ObtenerSesion().IdEntidad;
            if (idEntidad > 0) viewModel.IdEntidad = idEntidad;

            var servicios = new ServiciosReporte();
            var reporte = servicios.GenerarCadido(viewModel);

            var nombreReporte = ObtenerSesion().IdUsuario + "_reporte_cadido.xlsx";
            
            TempCarpeta.Guardar(reporte, nombreReporte);

            ViewBag.UbicacionReporte = ObtenerUrlAbsoluta(@"Archivos/Temp/" + nombreReporte);

            return View(viewModel);
        }
    }
}

Presentacion/Views/Shared/Cadido/_DetallesCadido.cshtml
<div class="modal fade" id="mdlDetalles" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">
                    <label>Detalles</label>
                </h3>
            </div>
            <div class="modal-body container-fluid">
                <div class="col-md-12 p-all-0">
                    <div class="widget-head-color-box p-xxs text-center">
                        <span class="bold" data-bind="text: Titulo"></span>
                    </div>
                    <div class="p-all-0 container-fluid">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-3 p-all-0 p-t-10">
                                    <span class="bold">Fondo:</span>
                                </div>
                                <div class="col-md-9 p-all-0 p-t-10">
                                    <span data-bind="text: Fondo"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0" id="detalle_subfondo">
                                <div class="col-md-3 p-all-0 p-t-10">
                                    Subfondo:
                                </div>
                                <div class="col-md-9 p-all-0 p-t-10">
                                    <span data-bind="text: Subfondo"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-3 p-all-0 p-t-10">
                                    <span class="bold">Sección:</span>
                                </div>
                                <div class="col-md-9 p-all-0 p-t-10">
                                    <span data-bind="text: Seccion"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0" id="detalle_subseccion">
                                <div class="col-md-3 p-all-0 p-t-10">
                                    Subsección:
                                </div>
                                <div class="col-md-9 p-all-0 p-t-10">
                                    <span data-bind="text: Subseccion"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-3 p-all-0 p-t-10">
                                    <span class="bold">Serie:</span>
                                </div>
                                <div class="col-md-9 p-all-0 p-t-10">
                                    <span data-bind="text: Serie"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0" id="detalle_subserie">
                                <div class="col-md-3 p-all-0 p-t-10">
                                    Subserie:
                                </div>
                                <div class="col-md-9 p-all-0 p-t-10">
                                    <span data-bind="text: Subserie"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6 p-all-0">
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span class="bold">Trámite</span>
                                </div>
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span data-bind="text: TiempoTramite"></span>
                                    <span> Años</span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span class="bold">Concentración:</span>
                                </div>
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span data-bind="text: TiempoConcentracion"></span>
                                    <span> Años</span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span class="bold">Clasificación información:</span>
                                </div>
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span data-bind="text: ClasificacionInformacion"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0" id="detalles_fundamento">
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span class="bold">Fundamento Legal:</span>
                                </div>
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span data-bind="text: FundamentoLegal"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span class="bold">Valor documental:</span>
                                </div>
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span data-bind="text: ValorDocumental"></span>
                                </div>
                            </div>
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span class="bold">Disposicion Documental</span>
                                </div>
                                <div class="col-md-6 p-all-0 p-t-10">
                                    <span data-bind="text: DisposicionDocumental"></span>
                                </div>
                            </div>                            
                            <div class="col-md-12 p-all-0">
                                <div class="col-md-12 p-t-10 p-all-0">
                                    <span class="bold" id="tituloFundamentoLegal"></span>
                                </div>
                                <div class="col-md-12 p-all-0 p-t-10">
                                    <span data-bind="text: DocumentalFundamentoLegal"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="/Scripts/knockout-2.2.0.js"></script>

<script type="text/javascript">
    var detallesCadido = (function () {

        function buscar(idCadido) {
            $.ajax({
                data: "{idCadido: '" + idCadido + "'}",
                dataType: "json",
                contentType: "application/json",
                type: "POST",
                url: '@Url.Action("Obtener", "Cadido", new { area = "Digitalizacion" })',
                beforeSend: function () {
                    MostrarDivCargando("Cargando detalles...");
                },
                success: function (data) {
                    ko.applyBindings(data);

                    if (data.IdDisposicionDocumental === 1) {
                        $("#tituloFundamentoLegal").text("Acuerdo de comite:");
                    }
                    if (data.IdDisposicionDocumental === 2) {
                        $("#tituloFundamentoLegal").text("Fundamento Legal:");
                    }

                    if (data.Subfondo === "") {
                        $("#detalle_subfondo").addClass("hidden");
                    } else {
                         $("#detalle_subfondo").removeClass("hidden");
                    }

                    if (data.Subseccion === "") {
                        $("#detalle_subseccion").addClass("hidden");
                    } else {
                        $("#detalle_subseccion").removeClass("hidden");
                    }

                    if (data.Subserie === "") {
                        $("#detalle_subserie").addClass("hidden");
                    } else {
                        $("#detalle_subserie").removeClass("hidden");
                    }

                    if (data.FundamentoLegal === "") {
                        $("#detalles_fundamento").addClass("hidden");
                    } else {
                        $("#detalles_fundamento").removeClass("hidden");
                    }

                    CerrarDivCargando();
                    $("#mdlDetalles").modal();
                },
                error: function (error) {
                    CerrarDivCargando();
                },
            });
        }

        return {
            Buscar: buscar
        };
    })();
</script>