Presentacion/Areas/Catalogo/Controllers/SeccionController.cs
using System;
using System.Web.Mvc;
using Datos;
using Datos.DTO.Infraestructura.ViewModels;
using Datos.Enums;
using Datos.Recursos;
using Datos.Repositorios.Configuracion;
using Presentacion.Controllers;
using Sistema.Extensiones;
using Sistema.Paginador;


namespace Presentacion.Areas.Catalogo.Controllers
{
    public class SeccionController : ControladorBase
    {
        public ActionResult Index(CuadroArchivisticoViewModel cuadroArchivisticoViewModel)
        {
            cuadroArchivisticoViewModel.CuadroArchivistico = new CuadroArchivistico {Habilitado = true};
            var idPadre = cuadroArchivisticoViewModel.IdPadre.DecodeFrom64().TryToInt();
            using (var bd = new Contexto())
            {
                var repositorio = new CuadroArchivisticoRepositorio(bd);

                if (idPadre > 0)
                {
                    var antecesores = repositorio.BuscarUnoSolo(a => a.IDCuadroArchivistico == idPadre,
                        new[]
                        {
                            "PadreCuadroArchivistico.PadreCuadroArchivistico"
                        });
                    cuadroArchivisticoViewModel.CuadroArchivistico.PadreCuadroArchivistico = antecesores;
                }

                cuadroArchivisticoViewModel.CuadroArchivistico.IDPadreCuadroArchivistico = idPadre;
                cuadroArchivisticoViewModel.CuadroArchivistico.IDTipoCuadroArchivistico =
                    (int) TiposCuadroArchivistico.Seccion;
                cuadroArchivisticoViewModel.CuadroArchivisticos =
                    repositorio.Buscar(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.TotalEncontrados =
                    repositorio.ObtenerTotalRegistros(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.Paginas =
                    Paginar.ObtenerCantidadPaginas(cuadroArchivisticoViewModel.TotalEncontrados,
                        cuadroArchivisticoViewModel.TamanoPagina);
            }

            return View(cuadroArchivisticoViewModel);
        }

        [HttpPost]
        public ActionResult Index(CuadroArchivisticoViewModel cuadroArchivisticoViewModel, string pagina)
        {
            if (string.IsNullOrEmpty(pagina)) pagina = "1";
            cuadroArchivisticoViewModel.PaginaActual = pagina.TryToInt();

            var idPadre = cuadroArchivisticoViewModel.IdPadre.DecodeFrom64().TryToInt();

            using (var bd = new Contexto())
            {
                var repositorio = new CuadroArchivisticoRepositorio(bd);

                if (idPadre > 0)
                {
                    var antecesores = repositorio.BuscarUnoSolo(a => a.IDCuadroArchivistico == idPadre,
                        new[]
                        {
                            "PadreCuadroArchivistico.PadreCuadroArchivistico"
                        });
                    cuadroArchivisticoViewModel.CuadroArchivistico.PadreCuadroArchivistico = antecesores;
                }

                cuadroArchivisticoViewModel.CuadroArchivistico.IDPadreCuadroArchivistico = idPadre;
                cuadroArchivisticoViewModel.CuadroArchivistico.IDTipoCuadroArchivistico =
                    (int) TiposCuadroArchivistico.Seccion;
                cuadroArchivisticoViewModel.CuadroArchivisticos =
                    repositorio.Buscar(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.TotalEncontrados =
                    repositorio.ObtenerTotalRegistros(cuadroArchivisticoViewModel);
                cuadroArchivisticoViewModel.Paginas = Paginar.ObtenerCantidadPaginas(
                    cuadroArchivisticoViewModel.TotalEncontrados,
                    cuadroArchivisticoViewModel.TamanoPagina);
            }
            LimpiarModelState();

            return View(cuadroArchivisticoViewModel);
        }

        public ActionResult Guardar(string idCuadroArchivistico, string idPadre)
        {
            var idCuadroArchivisticoBuscar = idCuadroArchivistico.DecodeFrom64().TryToInt();

            var viewModel = new GuardarCuadroArchivisticoViewModel {IdPadre = idPadre.DecodeFrom64().TryToInt()};

            using (var bd = new Contexto())
            {
                var cuadroarchivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);

                CuadroArchivistico cuadroArchivistico;
                if (idCuadroArchivisticoBuscar > 0)
                {
                    cuadroArchivistico = cuadroarchivisticoRepositorio
                        .BuscarPorIdCuadroArchivistico(idCuadroArchivisticoBuscar);
                    viewModel.EstablecerIdAntecesores(cuadroArchivistico);
                }
                else
                {
                    cuadroArchivistico = new CuadroArchivistico();

                    if (viewModel.IdPadre > 0)
                    {
                        var antecesores = cuadroarchivisticoRepositorio.BuscarUnoSolo(
                            a => a.IDCuadroArchivistico == viewModel.IdPadre,
                            new[]
                            {
                                "PadreCuadroArchivistico.PadreCuadroArchivistico"
                            });
                        viewModel.EstablecerIdAntecesores(antecesores);
                    }
                }
                viewModel.CuadroArchivistico = cuadroArchivistico;
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Guardar(GuardarCuadroArchivisticoViewModel viewModel, string idPadre)
        {
            var idCuadroArchivistico = ObtenerParametroGetEnInt(Enumerados.Parametro.IdCuadroArchivistico);
            viewModel.IdPadre = Request.QueryString["idPadre"].DecodeFrom64().TryToInt();

            var cuadroArchivistico = viewModel.CuadroArchivistico;

            if (viewModel.IdSubfondo > 0)
            {
                cuadroArchivistico.IDPadreCuadroArchivistico = viewModel.IdSubfondo;
            }
            else if (viewModel.IdFondo > 0)
            {
                cuadroArchivistico.IDPadreCuadroArchivistico = viewModel.IdFondo;
            }

            using (var bd = new Contexto())
            {
                AccionesAuditoria accion;
                var cuadroArchivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);
                cuadroArchivistico.IDCuadroArchivistico = idCuadroArchivistico;
                cuadroArchivistico.IDTipoCuadroArchivistico = (int) TiposCuadroArchivistico.Seccion;
                if (cuadroArchivistico.IDCuadroArchivistico > 0)
                {
                    cuadroArchivistico.FechaModificado = DateTime.Now;
                    cuadroArchivisticoRepositorio.Modificar(cuadroArchivistico);
                    EscribirCorrectoMensaje(General.GuardadoCorrecto);
                    accion = AccionesAuditoria.Modificar;
                }
                else
                {
                    cuadroArchivistico.Habilitado = true;
                    cuadroArchivistico.FechaCreacion = DateTime.Now;
                    cuadroArchivistico.FechaModificado = cuadroArchivistico.FechaCreacion;
                    cuadroArchivisticoRepositorio.Guardar(cuadroArchivistico);
                    EscribirCorrectoMensaje(General.GuardadoCorrecto);

                    accion = AccionesAuditoria.Guardar;
                }
                GuardarMovimientoAuditoria(cuadroArchivistico.IDCuadroArchivistico, ModulosAuditoria.Secciones, accion, cuadroArchivistico.Nombre);
                bd.SaveChanges();
            }

            dynamic parametrosGet;

            if (viewModel.IdPadre > 0)
                parametrosGet = new
                {
                    idCuadroArchivistico = cuadroArchivistico.IDCuadroArchivistico.ToString().EncodeTo64(),
                    idPadre = viewModel.IdPadre.ToString().EncodeTo64()
                };
            else
                parametrosGet = new { idCuadroArchivistico = cuadroArchivistico.IDCuadroArchivistico.ToString().EncodeTo64() };

            return RedirectToAction("Guardar", parametrosGet);
        }

        public ActionResult Habilitar(string idCuadroarchivistico, string idPadre)
        {
            var idCuadroarchivisticoHabilitar = idCuadroarchivistico.DecodeFrom64().TryToInt();

            using (var bd = new Contexto())
            {
                var cuadroarchivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);
                cuadroarchivisticoRepositorio.CambiarHabilitado(idCuadroarchivisticoHabilitar, true);
                EscribirCorrectoMensaje(General.HabilitadoCorrecto);
                GuardarMovimientoAuditoria(idCuadroarchivisticoHabilitar, ModulosAuditoria.Secciones, AccionesAuditoria.Habilitar);
                bd.SaveChanges();
            }
            return RedirectToAction("Index", new {idPadre});
        }

        public ActionResult Deshabilitar(string idCuadroarchivistico, string idPadre)
        {
            var idCuadroarchivisticoHabilitar = idCuadroarchivistico.DecodeFrom64().TryToInt();
            using (var bd = new Contexto())
            {
                var cuadroarchivisticoRepositorio = new CuadroArchivisticoRepositorio(bd);
                cuadroarchivisticoRepositorio.CambiarHabilitado(idCuadroarchivisticoHabilitar, false);
                EscribirCorrectoMensaje(General.DeshabilitadoCorrecto);
                GuardarMovimientoAuditoria(idCuadroarchivisticoHabilitar, ModulosAuditoria.Secciones, AccionesAuditoria.Habilitar);
                bd.SaveChanges();
            }
            return RedirectToAction("Index", new {idPadre});
        }       
    }
}

Presentacion/Areas/Catalogo/Views/Subfondo/Guardar.cshtml
@using Datos
@using Datos.Recursos
@using Datos.Repositorios.Configuracion
@using Presentacion.Helpers
@using Sistema.Extensiones
@model Datos.DTO.Infraestructura.ViewModels.GuardarCuadroArchivisticoViewModel

@{
    ViewBag.Title = General.GuardarSubFondo;
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-8 col-lg-7">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            @if (Model.CuadroArchivistico.IDCuadroArchivistico > 0)
                            {
                                <h5>Editar datos del nuevo subfondo</h5>
                            }
                            else
                            {
                                <h5>Datos del nuevo subfondo</h5>
                            }
                        </div>
                    </div>
                </div>
                <div class="ibox-content form-horizontal">
                    <div class="row">
                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.CuadroArchivistico.Clave, "Clave")
                        </div>
                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
                            @Html.TextBoxFor(m => m.CuadroArchivistico.Clave, new { @class = "form-control input-sm", @data_validation = "required,length", @data_validation_length = "max10", maxlength = "10" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.CuadroArchivistico.Nombre, "Nombre")
                        </div>
                        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
                            @Html.TextBoxFor(m => m.CuadroArchivistico.Nombre, new { @class = "form-control input-sm", @data_validation = "required,length", @data_validation_length = "max80", maxlength = "80" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-md-3">
                            <label for="IDPadreCuadroArchivistico">Fondo:</label>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @{
                                var fondos = CuadroArchivisticoRepositorio.BuscarTipo(TiposCuadroArchivistico.Fondo);
                                if (fondos.Count == 2) { Model.IdFondo = fondos.Last().Value.ToInt(); }
                            }
                            @Html.DropDownListFor(m => m.IdFondo, fondos, new { @class = "form-control input-sm" })
                        </div>
                    </div>
                </div>
                <div class="ibox-footer">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="pull-right">
                                @if (Model.IdPadre > 0)
                                {
                                    
                                    @Html.ActionLinkCifradoConTexto(General.Regresar, "Index", "Subfondo", "Catalogo", "btn btn-default btn-sm", "fa fa-angle-double-left",
                                        new Dictionary<string, int> { { "idPadre", Model.IdPadre } })
                                }
                                else
                                {
                                    @Html.ActionLinkCifradoConTexto(General.Regresar, "Index", "Subfondo", "Catalogo", "btn btn-default btn-sm", "fa fa-angle-double-left")
                                }                                
                                <button class="btn btn-primary btn-sm">
                                    <i class="fa fa-save"></i> @Resources.General.Guardar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<!-- Footer Scripts -->
@section FooterScripts{
    <script type="text/javascript">
        $.validate({
            language: es,
            modules: 'security'
        });
    </script>
}
<!-- End Footer Scripts -->

Presentacion/Areas/Catalogo/Views/Subfondo/Index.cshtml
@using Datos
@using Datos.Recursos
@using Datos.Repositorios.Configuracion
@using Presentacion.Helpers
@using Sistema.Extensiones

@model Datos.DTO.Infraestructura.ViewModels.CuadroArchivisticoViewModel

@{
    ViewBag.Title = Resources.General.BuscarSubfondo;
}

@using (Html.BeginForm())
{
    <div class="tarjeta">
        <div class="row">
            <div class="col-xs-12 col-md-6 form-horizontal">
                <div class="col-xs-12 col-md-12 form-horizontal">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-3">
                            <label for="CuadroArchivistico_Fondo">Clave:</label>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @Html.TextBoxFor(m => m.CuadroArchivistico.Clave, new { @class = "form-control input-sm" })
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12 form-horizontal">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-3">
                            &nbsp;
                        </div>
                        <div class="col-xs-12 col-md-9">
                            <div class="checkbox checkbox-success">
                                @Html.CheckBoxFor(m => m.CuadroArchivistico.Habilitado)
                                @Html.LabelFor(m => m.CuadroArchivistico.Habilitado)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-6 form-horizontal">
            @if (@Model.CuadroArchivistico.IDPadreCuadroArchivistico == 0)
            {
                <div class="col-xs-12 col-md-12 form-horizontal">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-3">
                            <label for="CuadroArchivistico_IDPadreCuadroArchivistico">Fondo:</label>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            @{
                                var fondos = CuadroArchivisticoRepositorio.BuscarTipo(TiposCuadroArchivistico.Fondo);
                                if(fondos.Count == 2) { Model.IdFondo = fondos.Last().Value.ToInt(); }
                            }
                            @Html.DropDownListFor(m => m.IdFondo, fondos, new {@class = "form-control input-sm"})
                        </div>
                    </div>
                </div>
            }
                <div class="col-xs-12 col-md-12">
                    @Html.ActionLinkCifradoConTexto("Nuevo", "Guardar", "Subfondo", "Catalogo",
                        "btn btn-sm btn-default pull-right m-l-5", "fa fa-plus",
                        new Dictionary<string, int> {{"IdPadre", Model.IdPadre.DecodeFrom64().TryToInt()}})
                    <button class="btn btn-sm btn-primary pull-right"><i class="fa fa-search"></i> @Resources.General.Buscar</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-12 m-t-10 m-b-10 ">
                <div class="col-md-6 bold">
                    @Html.DropDownListFor(m => m.TamanoPagina, Sistema.Listas.ObtenerListaCantidadPagina())
                    @Resources.General.TamanoPagina
                </div>
                <div class="col-md-6 text-right">
                    <label class="label label-success">
                        @Resources.General.Encontrados: @Model.TotalEncontrados
                    </label>
                </div>
            </div>
        </div>
        
        @if (Model.CuadroArchivistico.IDPadreCuadroArchivistico > 0)
        {
            <div class="row">
                <div class="col-xs-12 col-md-9 form-horizontal">
                    <div class="col-xs-12 col-md-12 form-horizontal">
                        <ul class="breadcrumb f-s-14">
                            <li>
                                @Html.ActionLinkCifradoConTexto("Cuadro Archivístico", "Index", "Fondo", "Catalogo", string.Empty, string.Empty)
                            </li>
                            <li>
                                @Html.ActionLinkCifradoConTexto(Model.CuadroArchivistico.PadreCuadroArchivistico.Nombre, "Index", "Subfondo", "Catalogo", string.Empty,
                                    string.Empty, new Dictionary<string, int> { { "idPadre", Model.CuadroArchivistico.IDPadreCuadroArchivistico ?? 0 } })
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        }

        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="table-responsive no-borders">
                    <table class="table table-hover table-striped min-w-700" id="tblBusqueda">
                        <thead>
                            <tr>
                                <th>Subfondo</th>
                                <th>Fondo</th>
                                <th>Fecha de creacion</th>
                                <th>Fecha de modificacion</th>
                                <th class="text-center">@Resources.General.Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var cuadroArchivistico in Model.CuadroArchivisticos)
                                {
                                    cuadroArchivistico.GenerarJerarquia();
                                    var subfondo = cuadroArchivistico.CuadroArchivistico;                                    
                                    <tr>
                                        <td>
                                            <strong>@subfondo.Clave></strong>
                                            <br/>
                                            @subfondo.Nombre
                                        </td>
                                        <td>
                                        <td>@subfondo.PadreCuadroArchivistico.Nombre</td>
                                        <td>@subfondo.FechaCreacion.Date.ToString("d")</td>
                                        <td>@subfondo.FechaModificado.Date.ToString("d")</td>
                                        <td class="text-center">
                                            @if (subfondo.Habilitado)
                                            {
                                                @Html.ActionLinkCifrado(General.Modificar, "Guardar", "Subfondo", "Catalogo",
                                                    "btn btn-warning btn-circle m-l-2 m-r-2", "fa fa-pencil",
                                                    new Dictionary<string, int> {
                                                        { "IDCuadroArchivistico", subfondo.IDCuadroArchivistico},
                                                        { "IdPadre", Model.IdPadre.DecodeFrom64().TryToInt()}
                                                })

                                                @Html.ActionLinkCifrado(Resources.General.Deshabilitar, "Deshabilitar", "Subfondo", "Catalogo",
                                                    "btn btn-danger btn-circle m-l-2 m-r-2 deshabilitar", "fa fa-times",
                                                    new Dictionary<string, int> { { "IDCuadroArchivistico", subfondo.IDCuadroArchivistico },
                                                        { "IdPadre", Model.IdPadre.DecodeFrom64().TryToInt()} }, new { @id = "btnEliminar", @name = subfondo.IDCuadroArchivistico })
                                            }
                                            else
                                            {
                                                @Html.ActionLinkCifrado(Resources.General.Habilitar, "Habilitar", "Subfondo", "Catalogo",
                                                    "btn btn-primary btn-circle habilitar", "fa fa-check",
                                                    new Dictionary<string, int> { { "IDCuadroArchivistico", subfondo.IDCuadroArchivistico },
                                                        { "IdPadre", Model.IdPadre.DecodeFrom64().TryToInt()} })
                                            }
                                            <a class="btn btn-success btn-circle" title="Ver secciones"
                                               href="@Url.Action("Index", "Seccion", new {idPadre = subfondo.IDCuadroArchivistico.ToString().EncodeTo64()})">
                                                Se
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <div>
                    @Html.Partial("Controls/_Paginacion", Model)
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    @section DocumentOnReady
    {
    $("#tblBusqueda").tablesorter();
    // Eventos
    $(document).off("click", "#btnEliminar");
    $(document).on("click", "#btnEliminar", function (e) {

        e.preventDefault();
        var href = this.href;

        swal({
            title: "¡Atención!",
            text: "¿Esta seguro que desea deshabilitar este Subfondo?",
            type: "warning",
            showCancelButton: true,
            cancelButtonText: "Cancelar",
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Aceptar",
            closeOnConfirm: false
        },
        function () {
            window.location.href = href;
            return true;
        });
    });
}
</script>